### Basic NumPy examples

In [ ]:
# import NumPy, np is the "standard" alias for numpy
# in conventional data analytics and ML code
import numpy as np

In [811]:
# RUN THIS CODE CELL IN ORDER TO USE THE CUSTOM STYLES
# THE ONLY PURPOSE OF THIS IS THE MAKE NUMPY ARRAYS
# VISUALLY MORE PLEASING
from IPython.core.interactiveshell import InteractiveShell

# Custom HTML formatter for NumPy arrays
# you can customize the color's if you wish!
# NOTE: this can be a bit buggy with some 
# more advanced NumPy operations, try removing
# this custom formatting code if problems arise

# NOTE: you can control the amount of decimals by changing 
# precision value below (9 is enough for the NumPy exercises)
def array_to_html(arr, precision=9):
    # Round the numbers to the specified precision and convert to string
    str_arr = np.round(arr, precision).astype(str)
    
    # Find the maximum width (longest string length)
    max_width = max([len(val) for val in str_arr.flatten()])
    
    # Create the HTML table with consistent column width and centered text
    html = "<table style='border: 1px solid black; border-collapse: collapse;'>"
    
    if arr.ndim == 1:
        # Handle 1D array (vector)
        for val in str_arr:
            html += f"<tr><td style='padding: 5px; border: 1px solid black; font-weight: bold; width: {max_width}ch; text-align: center;'>{val}</td></tr>"
    else:
        # Handle 2D array (matrix)
        for row in str_arr:
            html += "<tr>"
            for val in row:
                html += f"<td style='padding: 5px; border: 1px solid black; font-weight: bold; width: {max_width}ch; text-align: center;'>{val}</td>"
            html += "</tr>"
    
    html += "</table>"
    return html

# Register the formatter in IPython
InteractiveShell.instance().display_formatter.formatters['text/html'].for_type(
    np.ndarray, lambda arr: array_to_html(arr)
)

<function __main__.<lambda>(arr)>

### Data generators

In [812]:
# generate a vector (list)
data = np.arange(0, 10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [813]:
# we can also define a step size in order to skip numbers
# this example skips 4 numbers every time
# so from 0 -> 20 -> 0, 4, 8, 12, 16
data = np.arange(0, 20, 4)
data

array([ 0,  4,  8, 12, 16])

In [814]:
# NOTE! if you print NumPy data with print()
# you will not see any special styles (because printing
# is now done by Python instead of Jupyter)
print(data)

[ 0  4  8 12 16]


### You can convert conventional Python lists or lists-of-lists into NumPy arrays easily

In [815]:
# np.array is also handy if for some reason your
# data still remains in Python format, and your AI algorithm
# provides an error indicating your data is not in NumPy -format => np.array()
# often resolves this problem (but might need more features, like. np.expand_dims())
numbers = [6, 4, 8, 7, 2, 1, 3]
data = np.array(numbers)
data

array([6, 4, 8, 7, 2, 1, 3])

In [816]:
# example 2, list of lists
day1 = [-32, -29, -30, -31, -37]
day2 = [-5, -2, 0, 1, -6]
day3 = [-10, -14, -11, -12, -8]

# list of lists (matrix)
temperatures = [day1, day2, day3]

# convert to NumPy -format
data = np.array(temperatures)
data

array([[-32, -29, -30, -31, -37],
       [ -5,  -2,   0,   1,  -6],
       [-10, -14, -11, -12,  -8]])

### Some special data generators

In [817]:
# we can generate a collection of zeroes if we want
# this could be used to generate a set of default values
# for a real life dataset => usually 0 => "no"
data = np.zeros(8)
data

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [818]:
# a matrix version also possible:
data = np.zeros((5, 5))
data

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [819]:
# we can also change the data type into integer
# astype() is also usable most of the time in pandas
# very handy when the data is in a weird format (from a file etc.)
data = np.zeros((5, 5)).astype(int)
data

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [820]:
# we can generate a collection of ones too
# this could be used to generate a set of default values
# for a real life dataset => usually 1 => "yes"
data = np.ones((5, 5)).astype(int)
data

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### linspace => linearly spaced array

In [821]:
# without NumPy, you'd need a Python list,
# a for loop and division calculations

# linspace is often used in visualizations
# (modules like seaborn and matplotlib)
# in order to automatically accomodate the amount
# of data you wish to visualize
data = np.linspace(0, 10, 15)
data

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

### Random numbers in NumPy

In [822]:
# random number generation is often used
# in order to create imaginary test data for other modules
# like pandas and seaborn
# very practical if you need a smaller non-sense dataset
# in order to test your advanced data filtering/removal -algorithms
# before applying them into real datasets (to ensure you don't remove too much data)

# matrix version
data = np.random.rand(5, 5)
data

array([[0.12866485, 0.0070179 , 0.36511309, 0.29053927, 0.51440663],
       [0.42190701, 0.78648694, 0.3329849 , 0.52385928, 0.18410996],
       [0.88355426, 0.10538668, 0.85204532, 0.85377934, 0.34403978],
       [0.27546175, 0.38680649, 0.70470108, 0.8836047 , 0.64151535],
       [0.3745768 , 0.732129  , 0.29938458, 0.03618507, 0.38475137]])

In [823]:
# matrix version, values between 1-100 => 10 numbers
data = np.random.randint(1, 100, 10)
data

array([ 2, 28, 73,  7, 38, 31, 90, 51, 87, 88], dtype=int32)

In [824]:
# generate random numebrs from standard normal distribution
# value range is commonly between -3 and +3, not values slightly out of bounds
# also possible (meaning extreme values => outliers)
data = np.random.randn(5, 5)
data

array([[ 0.16260235,  0.40823858, -0.95379585,  1.87617496,  0.07425618],
       [ 0.61188995,  0.64020338,  1.56979476,  0.60566672,  0.01541192],
       [-0.40509739, -1.39187612, -0.24834152, -0.23702741,  0.87992927],
       [-1.15281226,  0.86050488, -0.91021919,  0.02657163, -1.202137  ],
       [ 1.50581017, -1.48610062,  1.46319673, -1.17291943, -1.65642536]])

In [825]:
# in future NumPy -versions the previous number examples
# might be removed, the new recommended way is to 
# use NumPy's random number generator
rng = np.random.default_rng()

# example to replace randn()
data = rng.normal(loc=0.0, scale=1.0, size=(5, 5))
data

array([[ 0.75246828,  0.06022576, -0.11211543,  1.02022838, -0.26934455],
       [ 0.16675752,  0.90824702, -0.24119879, -0.19624054, -1.87342839],
       [-0.36459293,  1.09822766, -0.24110286, -0.42029861, -0.63074706],
       [-0.56261866, -0.00887712, -0.68711442,  1.24578581, -1.23669835],
       [ 0.26665658, -0.74556485,  1.3430973 , -0.07428455,  0.10243668]])

In [826]:
# in future NumPy -versions the previous number examples
# might be removed, the new recommended way is to 
# use NumPy's random number generator
rng = np.random.default_rng()

# example to replace randn()
data = rng.integers(0, 100, size=25).reshape(5, 5)
data

array([[ 0, 67, 84, 31, 48],
       [78, 78, 15, 91,  3],
       [81, 87, 13, 64, 54],
       [14, 65, 57, 23, 59],
       [84, 77, 94, 77, 21]])

### reshape() -> convert any vector/list into a matrix!

In [827]:
# reshape() is very handy, as long as you have some kind of a vector (list)
# you can reshape it into a matrix easily (no need to remember specialized syntax)

# in this case we have 25 values (0-24) => 5 x 5 matrix (25 values)
# the values have to match, otherwise you'll get an error
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [828]:
# sometimes in ML etc. code, you might need to check
# your current data format in order to adapt it to your algorithm
data.shape

(5, 5)

In [829]:
# sometimes you also need to check what is the datatype
# a common bug => data looks like a number, but it's a text/object instead
data.dtype

dtype('int64')

### NumPy functions and tools

In [830]:
# some example data, random numbers between 1-100, 25 numbers => 5 x 5 matrix
data = np.random.randint(0, 100, 25).reshape(5, 5)
data

array([[19, 67, 11, 10, 48],
       [29, 56, 60, 20, 60],
       [41, 61, 79, 99, 45],
       [59, 88, 93, 68, 32],
       [21, 54, 63, 79, 22]], dtype=int32)

In [831]:
# getting the largest value in the dataset
max_value = data.max()
max_value

np.int32(99)

In [832]:
# getting the smallest value in the dataset
min_value = data.min()
min_value

np.int32(10)

In [833]:
# if you want remove the np.int32() wrapper
# from the print => just print directly
print(max_value)
print(min_value)

99
10


In [834]:
# argmax gives only a position as if the data was a vector (list)
# not needed commonly, except some specialized ML cases, see below
data.argmax()

np.int64(13)

In [835]:
# imaginary example, but realistic

# this example, we recognized hotel feedback, and
# whether it has a negative, neutral or positive tone

# indeces: 0 => negative, 1 => neutral, 2 => positive

# in AI code, we usually save the actual names of the values 
# since it's easier to understand when our code outputs "Neutral"
# instead of 1
categories = ["Negative", "Neutral", "Positive"]

# this is an imaginary output from a classification hotel feedback model
predictions = [0.37, 0.53, 0.97]

# convert into NumPy -array
data = np.array(predictions)

# get the index with the highest prediction in the list
highest_index = data.argmax()

# get the actual description of this result from the categories
result = categories[highest_index]
print(result)

Positive


### NumPy data indeces and selections / selectors ...

In [836]:
# example data
data = np.arange(0, 21, 2)
data

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [837]:
# single element, just like in Python
data[5]

np.int64(10)

In [838]:
# sublist of data also same as in Python
slice = data[3:7]
slice

array([ 6,  8, 10, 12])

In [839]:
# our new test dataset, a matrix
data = np.random.randint(0, 100, 25).reshape(5, 5)
data

array([[25, 31, 16, 31, 22],
       [54, 29, 31, 95, 82],
       [31, 32, 85, 17, 18],
       [96, 40, 78, 92, 15],
       [81, 59, 75, 84, 86]], dtype=int32)

In [840]:
# NumPy -version of row/column selection
# this example => row index 3, column index 4 
data[3, 4]

np.int32(15)

In [841]:
# data is now a matrix, sow one index => one row

# only the first row
data[0]

array([25, 31, 16, 31, 22], dtype=int32)

In [842]:
# means => all rows from start (index 0) => until index 2
# all columns after index 1

# see also the examples in the materials

# see the previously generated matrix for reference
# this is a aslice of the original matrix
data[:2, 1:]

array([[31, 16, 31, 22],
       [29, 31, 95, 82]], dtype=int32)

### Conditional filtering

In [843]:
# example data
data = np.arange(0, 11)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [844]:
# the recommended way to filter, use this syntax:
# this example => filter out values over 5
filtered = data[data > 5]
filtered

array([ 6,  7,  8,  9, 10])

In [845]:
# example two, numbers divisible by 2
filtered = data[data % 2 == 0]
filtered

array([ 0,  2,  4,  6,  8, 10])

### NumPy -slices and broadcasting

In [846]:
# example data
data = np.arange(0, 10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [847]:
# broadcast (override) the first elements to be 100
data[0:5] = 100
data

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [848]:
# let's take a slice of the data into a NEW VARIABLE
slice = data[0:5]
slice

array([100, 100, 100, 100, 100])

In [849]:
# replace the values only in the slice (not original data)
slice[:] = 150
slice

array([150, 150, 150, 150, 150])

In [850]:
# let's check the original data, see how broadcasting also
# changed the original data! this is not a bug, just a feature to manage memory
data

array([150, 150, 150, 150, 150,   5,   6,   7,   8,   9])

### Calculation operations

In [851]:
# our example data, imaginary salaries
salaries = np.arange(2000, 4000, 200)
salaries

array([2000, 2200, 2400, 2600, 2800, 3000, 3200, 3400, 3600, 3800])

In [852]:
# let's give a 150 € raise to everyone
salaries = salaries + 150

In [853]:
salaries

array([2150, 2350, 2550, 2750, 2950, 3150, 3350, 3550, 3750, 3950])

In [854]:
# let's also give another +10% increase
salaries = salaries * 1.1

In [855]:
salaries

array([2365., 2585., 2805., 3025., 3245., 3465., 3685., 3905., 4125.,
       4345.])

In [856]:
# broadcasting can be also used as a trick
# to generate certain values

# generate a bunch of ones => multiply all by 7
# => we have a bunch of 7s
data = np.ones(10).astype(int) * 7
data

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

### NaN / inf -values in NumPy data

In [857]:
# generate a dataset
data = np.arange(0 ,11)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [858]:
# NaN and inf-values are problematic, because they are unusable
# by ALL AI algorithms

# NaN => not a number => usually a missing value
result = data / data
result

C:\Users\tuomas.valtanen\AppData\Local\Temp\ipykernel_14604\355287934.py:5: RuntimeWarning: invalid value encountered in divide
  result = data / data


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [859]:
# inf => infinite value => very rare in real datasets
result = 1 / data
result

C:\Users\tuomas.valtanen\AppData\Local\Temp\ipykernel_14604\3443204991.py:2: RuntimeWarning: divide by zero encountered in divide
  result = 1 / data


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

### sum() etc. 

In [860]:
# new test data
values = np.arange(0, 100).reshape(10, 10)
values

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [861]:
# get total of all values
total = np.sum(values)
print(total)

4950


In [862]:
# get grouped sums based on columns, returns a vector (list)
# in pandas => axis-parameter is flipped
# means => axis = 1 => columns, axis = 0 => rows
total = np.sum(values, axis=0)
total


array([450, 460, 470, 480, 490, 500, 510, 520, 530, 540])

In [863]:
# get grouped sums based on ROWS, returns a vector (list)
total = np.sum(values, axis=1)
total


array([ 45, 145, 245, 345, 445, 545, 645, 745, 845, 945])

In [864]:
# standard deviation is sometimes used to determine
# the dataset optimization quality
# but pandas has better tools for this
deviation = np.std(values)
print(deviation)

28.86607004772212


**Extra: expand_dims() / squeeze()**

In [ ]:
# in ML, we sometimes need to modify the data structure to match ML
# algorithm requirements => expand_dims() and squeeze() are useful
predictions = [0.37, 0.53, 0.97]

# convert to NumPy-array
data = np.array(predictions)

# expand dimensions twice and reduce once
data = np.expand_dims(data, axis=1)
data = np.expand_dims(data, axis=1)
data = np.squeeze(data, axis=1)

print(data)

[[0.37]
 [0.53]
 [0.97]]
