### Basic NumPy examples

In [409]:
# improt NumPy, np is the "standard" alias for numpy
# in conventional data analytics and ML code
import numpy as np

In [410]:
# RUN THIS CODE CELL IN ORDER TO USE THE CUSTOM STYLES
# THE ONLY PURPOSE OF THIS IS THE MAKE NUMPY ARRAYS
# VISUALLY MORE PLEASING
from IPython.core.interactiveshell import InteractiveShell

# Custom HTML formatter for NumPy arrays
# you can customize the color's if you wish!
# NOTE: this can be a bit buggy with some 
# more advanced NumPy operations, try removing
# this custom formatting code if problems arise

# NOTE: you can control the amount of decimals by changing 
# precision value below (9 is enough for the NumPy exercises)
def array_to_html(arr, precision=9):
    # Round the numbers to the specified precision and convert to string
    str_arr = np.round(arr, precision).astype(str)
    
    # Find the maximum width (longest string length)
    max_width = max([len(val) for val in str_arr.flatten()])
    
    # Create the HTML table with consistent column width and centered text
    html = "<table style='border: 1px solid black; border-collapse: collapse;'>"
    
    if arr.ndim == 1:
        # Handle 1D array (vector)
        for val in str_arr:
            html += f"<tr><td style='padding: 5px; border: 1px solid black; font-weight: bold; width: {max_width}ch; text-align: center;'>{val}</td></tr>"
    else:
        # Handle 2D array (matrix)
        for row in str_arr:
            html += "<tr>"
            for val in row:
                html += f"<td style='padding: 5px; border: 1px solid black; font-weight: bold; width: {max_width}ch; text-align: center;'>{val}</td>"
            html += "</tr>"
    
    html += "</table>"
    return html

# Register the formatter in IPython
InteractiveShell.instance().display_formatter.formatters['text/html'].for_type(
    np.ndarray, lambda arr: array_to_html(arr)
)

<function __main__.<lambda>(arr)>

### Data generators

In [411]:
# generate a vector (list)
data = np.arange(0, 10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [412]:
# we can also define a step size in order to skip numbers
# this example skips 4 numbers every time
# so from 0 -> 20 -> 0, 4, 8, 12, 16
data = np.arange(0, 20, 4)
data

array([ 0,  4,  8, 12, 16])

In [413]:
# NOTE! if you print NumPy data with print()
# you will not see any special styles (because printing
# is now done by Python instead of Jupyter)
print(data)

[ 0  4  8 12 16]


### You can convert conventional Python lists or lists-of-lists into NumPy arrays easily

In [414]:
# np.array is also handy if for some reason your
# data still remains in Python format, and your AI algorithm
# provides an error indicating your data is not in NumPy -format => np.array()
# often resolves this problem (but might need more features, like. np.expand_dims())
numbers = [6, 4, 8, 7, 2, 1, 3]
data = np.array(numbers)
data

array([6, 4, 8, 7, 2, 1, 3])

In [415]:
# example 2, list of lists
day1 = [-32, -29, -30, -31, -37]
day2 = [-5, -2, 0, 1, -6]
day3 = [-10, -14, -11, -12, -8]

# list of lists (matrix)
temperatures = [day1, day2, day3]

# convert to NumPy -format
data = np.array(temperatures)
data

array([[-32, -29, -30, -31, -37],
       [ -5,  -2,   0,   1,  -6],
       [-10, -14, -11, -12,  -8]])

### Some special data generators

In [416]:
# we can generate a collection of zeroes if we want
# this could be used to generate a set of default values
# for a real life dataset => usually 0 => "no"
data = np.zeros(8)
data

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [417]:
# a matrix version also possible:
data = np.zeros((5, 5))
data

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [418]:
# we can also change the data type into integer
# astype() is also usable most of the time in pandas
# very handy when the data is in a weird format (from a file etc.)
data = np.zeros((5, 5)).astype(int)
data

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [419]:
# we can generate a collection of ones too
# this could be used to generate a set of default values
# for a real life dataset => usually 1 => "yes"
data = np.ones((5, 5)).astype(int)
data

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### linspace => linearly spaced array

In [420]:
# without NumPy, you'd need a Python list,
# a for loop and division calculations

# linspace is often used in visualizations
# (modules like seaborn and matplotlib)
# in order to automatically accomodate the amount
# of data you wish to visualize
data = np.linspace(0, 10, 15)
data

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

### Random numbers in NumPy

In [421]:
# random number generation is often used
# in order to create imaginary test data for other modules
# like pandas and seaborn
# very practical if you need a smaller non-sense dataset
# in order to test your advanced data filtering/removal -algorithms
# before applying them into real datasets (to ensure you don't remove too much data)

# matrix version
data = np.random.rand(5, 5)
data

array([[0.34844388, 0.54563651, 0.70616372, 0.57258966, 0.61028336],
       [0.89125791, 0.95574654, 0.99909731, 0.85126772, 0.10625069],
       [0.22943505, 0.61395094, 0.3455478 , 0.25690662, 0.3064392 ],
       [0.12026711, 0.56858579, 0.41674902, 0.77016273, 0.82530658],
       [0.54200751, 0.01811222, 0.76182835, 0.68255986, 0.23565089]])

In [422]:
# matrix version, values between 1-100 => 10 numbers
data = np.random.randint(1, 100, 10)
data

array([95, 25, 43, 92, 81, 64, 71, 68, 54, 38], dtype=int32)

In [423]:
# generate random numebrs from standard normal distribution
# value range is commonly between -3 and +3, not values slightly out of bounds
# also possible (meaning extreme values => outliers)
data = np.random.randn(5, 5)
data

array([[ 1.19437278,  0.03088898, -0.87971714, -0.34690804, -0.11301136],
       [-2.0259076 , -0.31379727,  2.61407299,  0.83503912,  0.97346592],
       [ 0.40167877, -0.83945887, -0.02201167,  0.08608976,  0.24729771],
       [-0.59672852, -0.65902601, -0.80683358,  0.47325561,  0.87349384],
       [-0.36582366,  0.12631998, -1.17817613, -0.55766369,  0.18601677]])

In [424]:
# in future NumPy -versions the previous number examples
# might be removed, the new recommended way is to 
# use NumPy's random number generator
rng = np.random.default_rng()

# example to replace randn()
data = rng.normal(loc=0.0, scale=1.0, size=(5, 5))
data

array([[-1.81823315, -1.65317754, -0.35228708,  0.92765274, -0.49733765],
       [ 0.5856146 , -0.25167879,  0.05557318,  1.71204739, -0.38187741],
       [-0.35366549,  0.9840678 ,  0.23979941, -0.83099141, -0.84535523],
       [ 0.072672  ,  0.18726322,  0.5917135 , -0.43569667,  1.85429884],
       [ 1.24498093, -0.85584462, -0.21698097,  0.71210852,  0.71235597]])

In [425]:
# in future NumPy -versions the previous number examples
# might be removed, the new recommended way is to 
# use NumPy's random number generator
rng = np.random.default_rng()

# example to replace randn()
data = rng.integers(0, 100, size=25).reshape(5, 5)
data

array([[22,  7, 35, 22, 72],
       [82, 62, 66, 77, 27],
       [62, 21, 40, 70, 56],
       [ 7, 72, 74, 42, 88],
       [33, 29, 17, 10, 57]])

### reshape() -> convert any vector/list into a matrix!

In [426]:
# reshape() is very handy, as long as you have some kind of a vector (list)
# you can reshape it into a matrix easily (no need to remember specialized syntax)

# in this case we have 25 values (0-24) => 5 x 5 matrix (25 values)
# the values have to match, otherwise you'll get an error
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [427]:
# sometimes in ML etc. code, you might need to check
# your current data format in order to adapt it to your algorithm
data.shape

(5, 5)

In [428]:
# sometimes you also need to check what is the datatype
# a common bug => data looks like a number, but it's a text/object instead
data.dtype

dtype('int64')

### NumPy functions and tools

In [429]:
# some example data, random numbers between 1-100, 25 numbers => 5 x 5 matrix
data = np.random.randint(0, 100, 25).reshape(5, 5)
data

array([[93, 79, 42, 45, 94],
       [ 3, 40, 87, 81, 75],
       [46, 80, 97, 76, 35],
       [12, 49, 36,  7, 27],
       [10, 41, 26, 50, 26]], dtype=int32)

In [430]:
# getting the largest value in the dataset
max_value = data.max()
max_value

np.int32(97)

In [431]:
# getting the smallest value in the dataset
min_value = data.min()
min_value

np.int32(3)

In [432]:
# if you want remove the np.int32() wrapper
# from the print => just print directly
print(max_value)
print(min_value)

97
3


In [433]:
# argmax gives only a position as if the data was a vector (list)
# not needed commonly, except some specialized ML cases, see below
data.argmax()

np.int64(12)

In [434]:
# imaginary example, but realistic

# this example, we recognized hotel feedback, and
# whether it has a negative, neutral or positive tone

# indeces: 0 => negative, 1 => neutral, 2 => positive

# in AI code, we usually save the actual names of the values 
# since it's easier to understand when our code outputs "Neutral"
# instead of 1
categories = ["Negative", "Neutral", "Positive"]

# this is an imaginary output from a classification hotel feedback model
predictions = [0.37, 0.53, 0.97]

# convert into NumPy -array
data = np.array(predictions)

# get the index with the highest prediction in the list
highest_index = data.argmax()

# get the actual description of this result from the categories
result = categories[highest_index]
print(result)

Positive
