### Basic NumPy examples

In [228]:
# improt NumPy, np is the "standard" alias for numpy
# in conventional data analytics and ML code
import numpy as np

In [229]:
# RUN THIS CODE CELL IN ORDER TO USE THE CUSTOM STYLES
# THE ONLY PURPOSE OF THIS IS THE MAKE NUMPY ARRAYS
# VISUALLY MORE PLEASING
from IPython.core.interactiveshell import InteractiveShell

# Custom HTML formatter for NumPy arrays
# you can customize the color's if you wish!
# NOTE: this can be a bit buggy with some 
# more advanced NumPy operations, try removing
# this custom formatting code if problems arise

# NOTE: you can control the amount of decimals by changing 
# precision value below (9 is enough for the NumPy exercises)
def array_to_html(arr, precision=9):
    # Round the numbers to the specified precision and convert to string
    str_arr = np.round(arr, precision).astype(str)
    
    # Find the maximum width (longest string length)
    max_width = max([len(val) for val in str_arr.flatten()])
    
    # Create the HTML table with consistent column width and centered text
    html = "<table style='border: 1px solid black; border-collapse: collapse;'>"
    
    if arr.ndim == 1:
        # Handle 1D array (vector)
        for val in str_arr:
            html += f"<tr><td style='padding: 5px; border: 1px solid black; font-weight: bold; width: {max_width}ch; text-align: center;'>{val}</td></tr>"
    else:
        # Handle 2D array (matrix)
        for row in str_arr:
            html += "<tr>"
            for val in row:
                html += f"<td style='padding: 5px; border: 1px solid black; font-weight: bold; width: {max_width}ch; text-align: center;'>{val}</td>"
            html += "</tr>"
    
    html += "</table>"
    return html

# Register the formatter in IPython
InteractiveShell.instance().display_formatter.formatters['text/html'].for_type(
    np.ndarray, lambda arr: array_to_html(arr)
)

<function __main__.<lambda>(arr)>

### Data generators

In [230]:
# generate a vector (list)
data = np.arange(0, 10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [231]:
# we can also define a step size in order to skip numbers
# this example skips 4 numbers every time
# so from 0 -> 20 -> 0, 4, 8, 12, 16
data = np.arange(0, 20, 4)
data

array([ 0,  4,  8, 12, 16])

In [232]:
# NOTE! if you print NumPy data with print()
# you will not see any special styles (because printing
# is now done by Python instead of Jupyter)
print(data)

[ 0  4  8 12 16]


### You can convert conventional Python lists or lists-of-lists into NumPy arrays easily

In [233]:
# np.array is also handy if for some reason your
# data still remains in Python format, and your AI algorithm
# provides an error indicating your data is not in NumPy -format => np.array()
# often resolves this problem (but might need more features, like. np.expand_dims())
numbers = [6, 4, 8, 7, 2, 1, 3]
data = np.array(numbers)
data

array([6, 4, 8, 7, 2, 1, 3])

In [234]:
# example 2, list of lists
day1 = [-32, -29, -30, -31, -37]
day2 = [-5, -2, 0, 1, -6]
day3 = [-10, -14, -11, -12, -8]

# list of lists (matrix)
temperatures = [day1, day2, day3]

# convert to NumPy -format
data = np.array(temperatures)
data

array([[-32, -29, -30, -31, -37],
       [ -5,  -2,   0,   1,  -6],
       [-10, -14, -11, -12,  -8]])

### Some special data generators

In [235]:
# we can generate a collection of zeroes if we want
# this could be used to generate a set of default values
# for a real life dataset => usually 0 => "no"
data = np.zeros(8)
data

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [236]:
# a matrix version also possible:
data = np.zeros((5, 5))
data

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [237]:
# we can also change the data type into integer
# astype() is also usable most of the time in pandas
# very handy when the data is in a weird format (from a file etc.)
data = np.zeros((5, 5)).astype(int)
data

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [238]:
# we can generate a collection of ones too
# this could be used to generate a set of default values
# for a real life dataset => usually 1 => "yes"
data = np.ones((5, 5)).astype(int)
data

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### linspace => linearly spaced array

In [239]:
# without NumPy, you'd need a Python list,
# a for loop and division calculations

# linspace is often used in visualizations
# (modules like seaborn and matplotlib)
# in order to automatically accomodate the amount
# of data you wish to visualize
data = np.linspace(0, 10, 15)
data

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

### Random numbers in NumPy

In [240]:
# random number generation is often used
# in order to create imaginary test data for other modules
# like pandas and seaborn
# very practical if you need a smaller non-sense dataset
# in order to test your advanced data filtering/removal -algorithms
# before applying them into real datasets (to ensure you don't remove too much data)

# matrix version
data = np.random.rand(5, 5)
data

array([[0.52047655, 0.08405704, 0.18912066, 0.91239766, 0.2237709 ],
       [0.49563389, 0.68228201, 0.2019419 , 0.88455022, 0.23596187],
       [0.30414319, 0.08531606, 0.27888629, 0.37281914, 0.05135423],
       [0.40749109, 0.75584802, 0.74213614, 0.10287582, 0.95203865],
       [0.15063001, 0.8090165 , 0.51284759, 0.68198238, 0.60729828]])

In [241]:
# matrix version, values between 1-100 => 10 numbers
data = np.random.randint(1, 100, 10)
data

array([87, 15, 75, 74, 72, 59, 90, 27, 37, 91], dtype=int32)

In [242]:
# generate random numebrs from standard normal distribution
# value range is commonly between -3 and +3, not values slightly out of bounds
# also possible (meaning extreme values => outliers)
data = np.random.randn(5, 5)
data

array([[ 0.54644584,  1.33377487,  0.28076785, -0.84614714, -0.07231485],
       [-1.52744387, -0.96298833, -1.0341326 ,  1.59421588,  0.57500385],
       [ 0.71017947,  1.03884937,  0.01106612, -0.38256232,  0.2555697 ],
       [ 0.86524895, -1.97158478, -1.11062225, -0.25606493, -0.64243291],
       [ 0.50710508,  0.34845688, -1.18202312, -0.53703731, -0.70207814]])

In [243]:
# in future NumPy -versions the previous number examples
# might be removed, the new recommended way is to 
# use NumPy's random number generator
rng = np.random.default_rng()

# example to replace randn()
data = rng.normal(loc=0.0, scale=1.0, size=(5, 5))
data

array([[ 0.76899448,  0.60670882, -1.39153155, -0.44617803,  1.29874866],
       [ 1.31172426,  0.43607385, -0.23834691,  0.98721654, -1.70811076],
       [-1.2954386 ,  1.31195006, -0.72974405,  0.36160163,  0.51478626],
       [ 0.15302841,  0.8279213 , -0.16744212, -1.00185721, -0.1343876 ],
       [-0.81446587,  0.91432968,  0.09838602, -0.63623477, -0.65812406]])

In [244]:
# in future NumPy -versions the previous number examples
# might be removed, the new recommended way is to 
# use NumPy's random number generator
rng = np.random.default_rng()

# example to replace randn()
data = rng.integers(0, 100, size=25).reshape(5, 5)
data

array([[60, 18, 15, 71, 18],
       [95, 55, 26, 75, 96],
       [40, 40, 60, 99, 98],
       [61, 27, 64,  2, 95],
       [78, 79, 44, 19, 52]])

### reshape() -> convert any vector/list into a matrix!

In [245]:
# reshape() is very handy, as long as you have some kind of a vector (list)
# you can reshape it into a matrix easily (no need to remember specialized syntax)

# in this case we have 25 values (0-24) => 5 x 5 matrix (25 values)
# the values have to match, otherwise you'll get an error
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [246]:
# sometimes in ML etc. code, you might need to check
# your current data format in order to adapt it to your algorithm
data.shape

(5, 5)

### NumPy functions and tools