### Basic NumPy examples

In [190]:
# improt NumPy, np is the "standard" alias for numpy
# in conventional data analytics and ML code
import numpy as np

In [191]:
# RUN THIS CODE CELL IN ORDER TO USE THE CUSTOM STYLES
# THE ONLY PURPOSE OF THIS IS THE MAKE NUMPY ARRAYS
# VISUALLY MORE PLEASING
from IPython.core.interactiveshell import InteractiveShell

# Custom HTML formatter for NumPy arrays
# you can customize the color's if you wish!
# NOTE: this can be a bit buggy with some 
# more advanced NumPy operations, try removing
# this custom formatting code if problems arise

# NOTE: you can control the amount of decimals by changing 
# precision value below (9 is enough for the NumPy exercises)
def array_to_html(arr, precision=9):
    # Round the numbers to the specified precision and convert to string
    str_arr = np.round(arr, precision).astype(str)
    
    # Find the maximum width (longest string length)
    max_width = max([len(val) for val in str_arr.flatten()])
    
    # Create the HTML table with consistent column width and centered text
    html = "<table style='border: 1px solid black; border-collapse: collapse;'>"
    
    if arr.ndim == 1:
        # Handle 1D array (vector)
        for val in str_arr:
            html += f"<tr><td style='padding: 5px; border: 1px solid black; font-weight: bold; width: {max_width}ch; text-align: center;'>{val}</td></tr>"
    else:
        # Handle 2D array (matrix)
        for row in str_arr:
            html += "<tr>"
            for val in row:
                html += f"<td style='padding: 5px; border: 1px solid black; font-weight: bold; width: {max_width}ch; text-align: center;'>{val}</td>"
            html += "</tr>"
    
    html += "</table>"
    return html

# Register the formatter in IPython
InteractiveShell.instance().display_formatter.formatters['text/html'].for_type(
    np.ndarray, lambda arr: array_to_html(arr)
)

<function __main__.<lambda>(arr)>

### Data generators

In [192]:
# generate a vector (list)
data = np.arange(0, 10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [193]:
# we can also define a step size in order to skip numbers
# this example skips 4 numbers every time
# so from 0 -> 20 -> 0, 4, 8, 12, 16
data = np.arange(0, 20, 4)
data

array([ 0,  4,  8, 12, 16])

In [194]:
# NOTE! if you print NumPy data with print()
# you will not see any special styles (because printing
# is now done by Python instead of Jupyter)
print(data)

[ 0  4  8 12 16]


### You can convert conventional Python lists or lists-of-lists into NumPy arrays easily

In [195]:
# np.array is also handy if for some reason your
# data still remains in Python format, and your AI algorithm
# provides an error indicating your data is not in NumPy -format => np.array()
# often resolves this problem (but might need more features, like. np.expand_dims())
numbers = [6, 4, 8, 7, 2, 1, 3]
data = np.array(numbers)
data

array([6, 4, 8, 7, 2, 1, 3])

In [196]:
# example 2, list of lists
day1 = [-32, -29, -30, -31, -37]
day2 = [-5, -2, 0, 1, -6]
day3 = [-10, -14, -11, -12, -8]

# list of lists (matrix)
temperatures = [day1, day2, day3]

# convert to NumPy -format
data = np.array(temperatures)
data

array([[-32, -29, -30, -31, -37],
       [ -5,  -2,   0,   1,  -6],
       [-10, -14, -11, -12,  -8]])

### Some special data generators

In [197]:
# we can generate a collection of zeroes if we want
# this could be used to generate a set of default values
# for a real life dataset => usually 0 => "no"
data = np.zeros(8)
data

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [198]:
# a matrix version also possible:
data = np.zeros((5, 5))
data

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [199]:
# we can also change the data type into integer
# astype() is also usable most of the time in pandas
# very handy when the data is in a weird format (from a file etc.)
data = np.zeros((5, 5)).astype(int)
data

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [200]:
# we can generate a collection of ones too
# this could be used to generate a set of default values
# for a real life dataset => usually 1 => "yes"
data = np.ones((5, 5)).astype(int)
data

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### linspace => linearly spaced array

In [201]:
# without NumPy, you'd need a Python list,
# a for loop and division calculations

# linspace is often used in visualizations
# (modules like seaborn and matplotlib)
# in order to automatically accomodate the amount
# of data you wish to visualize
data = np.linspace(0, 10, 15)
data

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

### Random numbers in NumPy

In [202]:
# random number generation is often used
# in order to create imaginary test data for other modules
# like pandas and seaborn
# very practical if you need a smaller non-sense dataset
# in order to test your advanced data filtering/removal -algorithms
# before applying them into real datasets (to ensure you don't remove too much data)

# matrix version
data = np.random.rand(5, 5)
data

array([[0.6366238 , 0.07842256, 0.05846443, 0.47515704, 0.38776541],
       [0.74613281, 0.86515705, 0.41651795, 0.49494566, 0.1954902 ],
       [0.54375   , 0.1025659 , 0.85097483, 0.23610945, 0.6017208 ],
       [0.9611427 , 0.25958646, 0.18427718, 0.69884946, 0.56560275],
       [0.37617797, 0.12176066, 0.23435909, 0.13823464, 0.02992561]])

In [203]:
# matrix version, values between 1-100 => 10 numbers
data = np.random.randint(1, 100, 10)
data

array([22, 40,  5, 85, 50,  8, 86, 60, 13, 51], dtype=int32)

In [204]:
# generate random numebrs from standard normal distribution
# value range is commonly between -3 and +3, not values slightly out of bounds
# also possible (meaning extreme values => outliers)
data = np.random.randn(5, 5)
data

array([[ 1.11214917, -0.57095037,  2.63137453,  2.56755352,  0.70397037],
       [ 0.77146303, -0.94974294, -1.54093709,  0.72259654,  0.17344945],
       [-1.42032015,  0.01684146, -0.24590545, -0.66766338, -2.3083899 ],
       [ 0.51521598, -1.05519923, -0.15085001,  0.04016157,  0.94159066],
       [-0.72846656, -0.42096741,  0.98911374, -0.60699611,  1.37133148]])

In [205]:
# in future NumPy -versions the previous number examples
# might be removed, the new recommended way is to 
# use NumPy's random number generator
rng = np.random.default_rng()

# example to replace randn()
data = rng.normal(loc=0.0, scale=1.0, size=(5, 5))
data

array([[-0.30144951, -1.26800562,  1.40290559,  0.97661595, -1.19872013],
       [ 1.05400398, -0.45996188,  1.06599445, -2.26694334, -0.07556648],
       [ 1.62235437, -0.10031867, -0.25420992,  0.01713456,  0.0466379 ],
       [ 0.14296853,  0.57654519,  0.56455552,  0.73351494, -0.37694902],
       [ 0.62549539,  0.92508425,  0.51513767, -0.85062228,  3.01411077]])

In [206]:
# in future NumPy -versions the previous number examples
# might be removed, the new recommended way is to 
# use NumPy's random number generator
rng = np.random.default_rng()

# example to replace randn()
data = rng.integers(0, 100, size=25).reshape(5, 5)
data

array([[70, 94,  6, 62, 52],
       [19, 94,  5, 34, 41],
       [42, 96, 90, 34, 58],
       [19,  6, 71, 49, 95],
       [98, 92, 20, 71, 82]])